package sk.uniba.fmph.dai.cats.events;

public enum EventType {
    ROOT_NOT_CREATED,
    MAX_DEPTH_REACHED,
    PROCESSING_NODE,
    CHILDLESS_NODE,
    EDGE_CREATED,
    INVALID_PATH,
    EDGE_PRUNED,
    EXPLANATION_EDGE,
    IRELEVANT_EXPLANATION,
    INCONSISTENT_EXPLANATION,
    NONMINIMAL_EXPLANATION,
    POSSIBLE_EXPLANATION,
    CLOSING_NODE,
    MODEL_REUSE,
    NODE_CREATED,
    TREE_FINISHED,
    LEVEL_FINISHED,
    LEVEL_STARTED,
    CONSISTENCY_CHECK,
    MODEL_EXTRACTION,
    MODEL_STORED,
    MXP_CALL,
    QXP_CALL

}
